version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DB=dacs2
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dacs2
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dacs2.sql:/docker-entrypoint-initdb.d/dacs2.sql
volumes:
  db_data:
